version: "3.8"

services:
  db:
    image: postgres:11.8
    restart: always
    container_name: "karmabot_postgres"
    environment:
      - POSTGRES_USER=user42
      - POSTGRES_PASSWORD=pw42
      - POSTGRES_DB=karmabot
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
