name: Coverage

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: install nox
        run: pip install nox==2022.11.21

      - name: install poetry
        run: pip install poetry==1.3.2

      - name: run coverage
        run: nox --sessions tests-3.10 coverage

      - name: codecov
        uses: codecov/codecov-action@v2
