name: Coverage
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: x64
      - run: pip install nox==2020.12.31
      - run: pip install poetry==1.1.6
      - run: nox --sessions tests-3.8 coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
