name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Install Poetry
        run: poetry install

      - name: Configure Poetry
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"

      - name: Publish package
        run: poetry publish --build
