name: Safety

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    name: Python ${{ matrix.python-version }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: install nox
        run: pip install nox==2021.6.12

      - name: install poetry
        run: pip install poetry==1.1.7

      - name: run safety
        run: nox --sessions safety-${{ matrix.python-version }}
